### ISSUE TITLE
where is babel.cfg?

### ISSUE THREAD

**Issue by luckypoem** [jokull/jinjet#1]
hi.

git clone https://github.com/jokull/jinjet.git
cd jinjet
as3:~/jinjet# python setup.py install
as3:~/jinjet# ls
build  jinjet.egg-info  LICENSE    requirements.txt
dist   jinjet.py        README.md  setup.py
as3:~/jinjet# ls dist
jinjet-0.1-py2.6.egg
as3:~/jinjet# ls build
bdist.linux-i686  lib.linux-i686-2.6
as3:~/jinjet# jinjet -v
Could not find Babel conf (babel.cfg)
as3:~/jinjet# find / -name babel.cfg
as3:~/jinjet#

tks for ur reply.

**Comment by jokull** [comment]
You should create your own babel.cfg to suit your needs:

```
$ cat babel.cfg
[jinja2: **/assets/**.html]
extensions=jinja2.ext.autoescape,jinja2.ext.with_
```
